# Generated by Django 2.2 on 2019-11-09 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carpeta', models.CharField(max_length=100)),
                ('link_drive', models.URLField()),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectino.Proyectino')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField(blank=True)),
                ('fecha_fin', models.DateField(blank=True)),
                ('documentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Documento')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoProyectino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField(help_text='fecha en la que ingreso el proyectino al proyecto')),
                ('fecha_salida', models.DateField(help_text='fecha en la que salio el proyectino del proyecto')),
                ('proyectino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectino.Proyectino')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Tipo'),
        ),
    ]
