# Generated by Django 2.2 on 2019-11-09 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_esp', models.CharField(max_length=30)),
                ('nombre_facu', models.CharField(help_text='aquí irá el nombre completo de la facultad y no de forma abreviada', max_length=75)),
                ('abreviaura', models.CharField(help_text='aquí irá las siglas de la facu', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proyectino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('lastname', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=75)),
                ('celular', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateField(blank=True)),
                ('fecha_nacimiento', models.DateField(blank=True)),
                ('dni', models.CharField(max_length=10)),
                ('cod_uni', models.CharField(help_text='este será el código de la uni de cada estudiante', max_length=10)),
                ('estado', models.CharField(help_text='indica el estado activo/inactivo/honoraio.. de un miembro', max_length=75)),
                ('cantidad_toribonus', models.IntegerField()),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectino.Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_toribonu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Toribonu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(help_text='nombre de la persona que está asignando los toribonus', max_length=75)),
                ('descripcion', models.CharField(max_length=75)),
                ('cantidad', models.IntegerField()),
                ('proyectino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectino.Proyectino')),
                ('tipo_toribonu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectino.Tipo_toribonu')),
            ],
        ),
        migrations.CreateModel(
            name='Certificacion_proyectino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('fecha_certificación', models.CharField(max_length=75)),
                ('proyectino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectino.Proyectino')),
            ],
        ),
    ]
