# Generated by Django 2.2 on 2020-01-25 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectino',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Directiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=25)),
                ('periodo', models.IntegerField()),
                ('avatar_landing', models.ImageField(blank=True, null=True, upload_to='')),
                ('gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectino.Proyectino')),
            ],
        ),
    ]
