# Generated by Django 2.2.6 on 2019-11-09 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApellidoPaterno', models.CharField(max_length=40)),
                ('ApellidoMaterno', models.CharField(max_length=40)),
                ('Nombres', models.CharField(max_length=40)),
                ('DNI', models.CharField(max_length=9)),
                ('FechaNacimiento', models.DateField()),
                ('Sexo', models.CharField(choices=[('f', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Categoría', models.CharField(max_length=50)),
                ('Estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripción',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaMatrícula', models.DateTimeField(auto_now_add=True)),
                ('Alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Proyectino')),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Proyecto')),
            ],
        ),
    ]
